### ISSUE TITLE
Advise about syntesing from style tokens?

### ISSUE THREAD

**Issue by hadaev8** [jinhan/tacotron2-gst#2]
My code is based on the current repository Nvidia tacotron2 and I used your GST code.
Using ref audio work more or less, but I can't get to work style tokens.
It looks like this
https://i.imgur.com/wK7vZ73.png

**Comment by jinny1208** [comment]
Have you solved your problem? How were you able to get GST to work?

**Comment by hadaev8** [comment]
@hadaev8 Yes, I made it work.
Don't remember whats the problem on my screen.
